{
 "title": "Kafka Event Processing – Observability Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Events Processed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events processed per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(events_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Failed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(events_failed_total/3)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Failed per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(events_failed_total[2m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events sent to DLQ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_dlq_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events sent to DLQ (last 5 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rate(events_dlq_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum by (consumergroup) (\r\n  kafka_topic_partition_current_offset\r\n  -\r\n  on (topic, partition)\r\n  kafka_consumergroup_current_offset\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}